In [37]:
import pandas as pd 
import ast

In [3]:
df = pd.read_csv("/Users/baselhussein/Projects/pps/data/Longform.csv")

In [13]:
df

,ID,Session_timestamp,Level_timestamp,Event_type,Event,Level,Details,filename,epoch_time,object_orientation,x_coordinate,y_coordinate,objects,Session_number,Level_progression,Ruleset,Levels_complete,LevelTime,SessionTime,drop
0,100,0:0:0:000,0:0:0:000,event,session_start,NaN,26/01/2022 18:02:52,100_0.txt,1.643220e+12,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,100,0:0:9:583,0:0:0:000,event,start,0level:baba is you,NaN,100_0.txt,1.643220e+12,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,100,0:0:9:583,0:0:0:000,event,init_object,0level:baba is you,text_baba:12:7,100_0.txt,1.643220e+12,NaN,12.0,7.0,text_baba,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100,0:0:9:583,0:0:0:000,event,init_object,0level:baba is you,wall:12:9,100_0.txt,1.643220e+12,NaN,12.0,9.0,wall,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100,0:0:9:583,0:0:0:000,event,init_object,0level:baba is you,tile:12:10,100_0.txt,1.643220e+12,NaN,12.0,10.0,tile,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12358948,99,0:15:4:200,0:0:0:033,event,new_object,177level:1. the lake,line:15:13,99_4.txt,1.644423e+12,NaN,15.0,13.0,line,NaN,NaN,NaN,"['0level:baba is you', '1level:where do i go?'...",NaN,NaN,NaN
12358949,99,0:15:4:200,0:0:0:033,event,new_object,177level:1. the lake,line:15:14,99_4.txt,1.644423e+12,NaN,15.0,14.0,line,NaN,NaN,NaN,"['0level:baba is you', '1level:where do i go?'...",NaN,NaN,NaN
12358950,99,0:15:4:200,0:0:0:033,event,new_object,177level:1. the lake,line:15:9,99_4.txt,1.644423e+12,NaN,15.0,9.0,line,NaN,NaN,NaN,"['0level:baba is you', '1level:where do i go?'...",NaN,NaN,NaN
12358951,99,0:15:4:200,0:0:0:033,event,new_object,177level:1. the lake,line:13:10,99_4.txt,1.644423e+12,NaN,13.0,10.0,line,NaN,NaN,NaN,"['0level:baba is you', '1level:where do i go?'...",NaN,NaN,NaN
12358952,99,0:15:28:883,0:0:24:716,input,end,177level:1. the lake,NaN,99_4.txt,1.644423e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['0level:baba is you', '1level:where do i go?'...",NaN,NaN,NaN

In [16]:
df_levels_complete = df.dropna(subset=['Levels_complete'])
df_levels_complete

,ID,Session_timestamp,Level_timestamp,Event_type,Event,Level,Details,filename,epoch_time,object_orientation,x_coordinate,y_coordinate,objects,Session_number,Level_progression,Ruleset,Levels_complete,LevelTime,SessionTime,drop
93,100,0:0:56:466,0:0:46:883,event,win,0level:baba is you,NaN,100_0.txt,1.643220e+12,NaN,NaN,NaN,NaN,NaN,NaN,"['baba is you ', 'wall is stop ', 'flag is win...",['0level:baba is you'],46883.0,NaN,NaN
94,100,0:0:56:466,0:0:46:883,input,right,0level:baba is you,NaN,100_0.txt,1.643220e+12,NaN,NaN,NaN,NaN,NaN,NaN,"['baba is you ', 'wall is stop ', 'flag is win...",['0level:baba is you'],NaN,NaN,NaN
95,100,0:0:59:300,0:0:0:000,event,start,106level:map,NaN,100_0.txt,1.643220e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['0level:baba is you'],NaN,NaN,NaN
96,100,0:0:59:300,0:0:0:000,event,init_object,106level:map,flower:12:8,100_0.txt,1.643220e+12,NaN,12.0,8.0,flower,NaN,NaN,NaN,['0level:baba is you'],NaN,NaN,NaN
97,100,0:0:59:300,0:0:0:000,event,init_object,106level:map,flower:13:9,100_0.txt,1.643220e+12,NaN,13.0,9.0,flower,NaN,NaN,NaN,['0level:baba is you'],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12358948,99,0:15:4:200,0:0:0:033,event,new_object,177level:1. the lake,line:15:13,99_4.txt,1.644423e+12,NaN,15.0,13.0,line,NaN,NaN,NaN,"['0level:baba is you', '1level:where do i go?'...",NaN,NaN,NaN
12358949,99,0:15:4:200,0:0:0:033,event,new_object,177level:1. the lake,line:15:14,99_4.txt,1.644423e+12,NaN,15.0,14.0,line,NaN,NaN,NaN,"['0level:baba is you', '1level:where do i go?'...",NaN,NaN,NaN
12358950,99,0:15:4:200,0:0:0:033,event,new_object,177level:1. the lake,line:15:9,99_4.txt,1.644423e+12,NaN,15.0,9.0,line,NaN,NaN,NaN,"['0level:baba is you', '1level:where do i go?'...",NaN,NaN,NaN
12358951,99,0:15:4:200,0:0:0:033,event,new_object,177level:1. the lake,line:13:10,99_4.txt,1.644423e+12,NaN,13.0,10.0,line,NaN,NaN,NaN,"['0level:baba is you', '1level:where do i go?'...",NaN,NaN,NaN
12358952,99,0:15:28:883,0:0:24:716,input,end,177level:1. the lake,NaN,99_4.txt,1.644423e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['0level:baba is you', '1level:where do i go?'...",NaN,NaN,NaN

In [27]:
def find_levels_completed(student): 
    longest_list = max(student['Levels_complete'], key=len)
    return pd.Series({
        #'count_levels_complete': len(longest_list),  
        'levels_complete': longest_list  
    })

In [36]:
# Apply the function to each group of 'ID'
df_levels_complete_count = df_levels_complete.groupby('ID').apply(find_levels_completed).reset_index()
df_levels_complete_count

      ID                                    levels_complete
0      1  ['0level:baba is you', '1level:where do i go?'...
1      2  ['0level:baba is you', '1level:where do i go?'...
2      3  ['0level:baba is you', '1level:where do i go?'...
3      5  ['0level:baba is you', '1level:where do i go?'...
4      6  ['0level:baba is you', '1level:where do i go?'...
..   ...                                                ...
180  254  ['0level:baba is you', '1level:where do i go?'...
181  255  ['0level:baba is you', '1level:where do i go?'...
182  256  ['0level:baba is you', '1level:where do i go?'...
183  257  ['236level:changeless', '136level:jelly throne...
184  258  ['5level:off limits', '6level:grass yard', '20...

[185 rows x 2 columns]

In [38]:
# Function to convert strings to actual lists
def convert_to_list(row):
    if isinstance(row['levels_complete'], str):
        return ast.literal_eval(row['levels_complete'])
    return row['levels_complete']

# Apply the function to convert strings to lists
df_levels_complete_count['levels_complete'] = df_levels_complete_count.apply(convert_to_list, axis=1)

In [39]:
# Function to count the number of items in a list
def count_items_in_list(row):
    return len(row['levels_complete'])

# Apply the function to count items in each list and create a new column 'list_length'
df_levels_complete_count['len_levels_complete'] = df_levels_complete_count.apply(count_items_in_list, axis=1)

In [40]:
df_levels_complete_count

,ID,levels_complete,len_levels_complete
0,1,"[0level:baba is you, 1level:where do i go?, 18...",7
1,2,"[0level:baba is you, 1level:where do i go?, 18...",35
2,3,"[0level:baba is you, 1level:where do i go?, 18...",8
3,5,"[0level:baba is you, 1level:where do i go?, 18...",9
4,6,"[0level:baba is you, 1level:where do i go?, 18...",36
...,...,...,...
180,254,"[0level:baba is you, 1level:where do i go?, 18...",9
181,255,"[0level:baba is you, 1level:where do i go?, 18...",23
182,256,"[0level:baba is you, 1level:where do i go?, 18...",9
183,257,"[236level:changeless, 136level:jelly throne, 0...",19
184,258,"[5level:off limits, 6level:grass yard, 20level...",13

In [41]:
df_levels_complete_count.to_csv('/Users/baselhussein/Projects/impossible_goals/agg/data/id_levels_complete.csv', index=False)